import request from "supertest";
import { describe, expect, it } from "vitest";
import { createApp } from "../server/app.js";
import { roles } from "../shared/permissions.js";

class Users { constructor(){this.users=new Map([["admin",{id:"u1",agencyId:"a1",isActive:true,role:{name:roles.ADMIN},assignments:[]}],["manager",{id:"u2",agencyId:"a1",isActive:true,role:{name:roles.MANAGER},assignments:[{clientId:"c1"}]}],["client",{id:"u3",agencyId:"a1",isActive:true,role:{name:roles.CLIENT},clientId:"c1",assignments:[]}]]);} async findUserBySupabaseAuthId(id){return this.users.get(id)??null;} }
class Auth { async verifyAccessToken(token){return {id:token,email:`${token}@test`};} }
class ClientRepo { constructor(){this.clients=[];this.contacts=[];this.notes=[];this.assignments=[];this.activities=[];this.team=new Map([["u2",{id:"u2",agencyId:"a1",role:{name:roles.MANAGER}}]]);} async listClients(){return this.clients.map(c=>({...c,contacts:this.contacts,notes:this.notes,assignments:this.assignments,websites:[]}));} async findClientById(id){const c=this.clients.find(x=>x.id===id);return c?{...c,contacts:this.contacts,notes:this.notes,assignments:this.assignments,websites:[]}:null;} async createClient(data){const c={id:`c${this.clients.length+1}`,...data,contacts:[],notes:[],assignments:[],websites:[]};this.clients.push(c);return c;} async updateClient(id,data){Object.assign(this.clients.find(c=>c.id===id),data);return this.findClientById(id);} async deleteClient(id){this.clients=this.clients.filter(c=>c.id!==id);return {id};} async createContact(clientId,data){const c={id:"contact1",clientId,...data};this.contacts.push(c);return c;} async createNote(clientId,authorId,note){const n={id:"note1",clientId,authorId,note};this.notes.push(n);return n;} async findUserInAgency(id,agencyId){const user=this.team.get(id);return user?.agencyId===agencyId?user:null;} async assignUser(clientId,userId){const a={id:"assign1",clientId,userId};this.assignments.push(a);return a;} async createActivity(data){this.activities.push(data);return data;} }
function app(repo=new ClientRepo()){return {app:createApp({userRepository:new Users(),authProvider:new Auth(),clientRepository:repo}),repo};}

describe("client and team management",()=>{
 it("creates clients, contacts, notes, assignments, and activity logs",async()=>{const setup=app();const created=await request(setup.app).post("/api/v1/clients").set("Authorization","Bearer admin").send({companyName:"Acme SEO",retainerAmount:1200,retainerCycle:"monthly"});expect(created.status).toBe(201);expect(created.body.client.healthScore).toBeGreaterThan(0);await request(setup.app).post("/api/v1/clients/c1/contacts").set("Authorization","Bearer admin").send({name:"A",email:"a@test.com"});await request(setup.app).post("/api/v1/clients/c1/notes").set("Authorization","Bearer admin").send({note:"Internal note"});const assigned=await request(setup.app).post("/api/v1/clients/c1/assignments").set("Authorization","Bearer admin").send({userId:"u2"});expect(assigned.status).toBe(201);expect(setup.repo.activities.map(a=>a.action)).toEqual(expect.arrayContaining(["client.created","client.contact_added","client.note_added","client.assigned"]));});
 it("hides internal fields from client role",async()=>{const setup=app();await request(setup.app).post("/api/v1/clients").set("Authorization","Bearer admin").send({companyName:"Acme SEO",retainerAmount:1200,retainerCycle:"monthly"});const response=await request(setup.app).get("/api/v1/clients/c1").set("Authorization","Bearer client");expect(response.status).toBe(200);expect(response.body.client.retainerAmount).toBeUndefined();expect(response.body.client.notes).toBeUndefined();});
});
