import request from "supertest";
import { describe, expect, it } from "vitest";
import { createApp } from "../server/app.js";
import { roles } from "../shared/permissions.js";

class Users { constructor(){this.users=new Map([["admin",{id:"u1",agencyId:"a1",isActive:true,role:{name:roles.ADMIN},assignments:[]}],["manager",{id:"u2",agencyId:"a1",isActive:true,role:{name:roles.MANAGER},assignments:[{clientId:"c1"}]}],["client",{id:"u3",agencyId:"a1",isActive:true,role:{name:roles.CLIENT},clientId:"c1",assignments:[]}]]);} async findUserBySupabaseAuthId(id){return this.users.get(id)??null;} }
class Auth { async verifyAccessToken(token){return {id:token,email:`${token}@test`};} }
class Repo { constructor(){this.clients=new Map([["c1",{id:"c1",agencyId:"a1",companyName:"Acme"}]]);this.websites=[];this.competitors=[];this.links=[];this.activities=[];} async findClientById(id){return this.clients.get(id)??null;} async findWebsiteById(id){const w=this.websites.find(x=>x.id===id);return w?{...w,client:this.clients.get(w.clientId),competitors:this.competitors.filter(c=>c.websiteId===id).map(c=>({...c,backlinks:this.links.filter(l=>l.competitorId===c.id)}))}:null;} async listWebsites(where){return this.websites.filter(w=>w.clientId===where.clientId).map(w=>({...w,client:this.clients.get(w.clientId),competitors:[]}));} async createWebsite(data){const w={id:`w${this.websites.length+1}`,createdAt:new Date(),...data,client:this.clients.get(data.clientId),competitors:[]};this.websites.push(w);return w;} async updateWebsite(id,data){Object.assign(this.websites.find(w=>w.id===id),data);return this.findWebsiteById(id);} async deleteWebsite(id){this.websites=this.websites.filter(w=>w.id!==id);return {id};} async createCompetitor(data){const c={id:`comp${this.competitors.length+1}`,...data,backlinks:[]};this.competitors.push(c);return c;} async findCompetitorById(id){const c=this.competitors.find(x=>x.id===id);const w=await this.findWebsiteById(c?.websiteId);return c?{...c,website:w,backlinks:this.links.filter(l=>l.competitorId===id)}:null;} async updateCompetitor(id,data){Object.assign(this.competitors.find(c=>c.id===id),data);return this.findCompetitorById(id);} async deleteCompetitor(id){this.competitors=this.competitors.filter(c=>c.id!==id);return {id};} async createCompetitorBacklink(competitorId,data){const link={id:"link1",competitorId,...data};this.links.push(link);return link;} async createActivity(data){this.activities.push(data);return data;} }
function app(repo=new Repo()){return {app:createApp({userRepository:new Users(),authProvider:new Auth(),websiteRepository:repo}),repo};}

describe("website and competitor management",()=>{
 it("creates website workspaces and competitor backlink placeholders",async()=>{const setup=app();const website=await request(setup.app).post("/api/v1/clients/c1/websites").set("Authorization","Bearer manager").send({domain:"acme.test",cms:"WordPress",businessCategory:"SaaS",targetLocations:["US"],targetSearchEngines:["google"],preferredLocale:"en-US"});expect(website.status).toBe(201);expect(website.body.website.tabs.map(t=>t.tab)).toEqual(expect.arrayContaining(["overview","keywords","audits","competitors","backlinks","content","tasks","reports"]));const competitor=await request(setup.app).post(`/api/v1/websites/${website.body.website.id}/competitors`).set("Authorization","Bearer manager").send({domain:"rival.test",name:"Rival"});expect(competitor.status).toBe(201);expect(setup.repo.links).toHaveLength(1);});
 it("blocks clients from website mutation",async()=>{const setup=app();const response=await request(setup.app).post("/api/v1/clients/c1/websites").set("Authorization","Bearer client").send({domain:"blocked.test"});expect(response.status).toBe(403);});
});
