export const dayOneSchemaGroups = Object.freeze({
  core: ["Agency", "Role", "User", "Client", "ClientContact", "ClientAssignment", "ClientNote"],
  seo: [
    "Website",
    "Competitor",
    "CompetitorKeyword",
    "CompetitorPage",
    "CompetitorBacklink",
    "KeywordGroup",
    "Keyword",
    "KeywordRanking",
    "SerpSnapshot",
    "SerpFeature",
    "Backlink",
    "CrawlRun",
    "CrawledUrl",
    "TechnicalCheck",
    "PageMetric",
  ],
  workflow: ["Project", "Task", "TaskComment", "TaskAttachment", "Activity", "Alert", "Notification"],
  reporting: ["Report", "ReportTemplate", "ScheduledReport"],
  content: ["ContentCluster", "ContentBrief", "ContentCalendarItem"],
  integrations: ["Integration", "IntegrationSyncLog", "DataSource"],
  ai: ["AiRequest"],
});

export const migrationOrder = [
  "core",
  "clients",
  "websites",
  "competitors",
  "keywords",
  "serp",
  "crawlAndAudit",
  "tasksAndActivities",
  "contentPlanning",
  "reporting",
  "alertsAndNotifications",
  "integrationsAndSyncLogs",
  "aiRequests",
];