import { access, mkdir } from "node:fs/promises";
import path from "node:path";

import puppeteer from "puppeteer";

import { env } from "../config/env.js";

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function number(value) {
  return new Intl.NumberFormat("en-US").format(Number(value ?? 0));
}

function metric(label, value) {
  return `<div class="metric"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong></div>`;
}

function list(items, emptyText) {
  if (!items?.length) return `<p class="empty">${escapeHtml(emptyText)}</p>`;
  return `<ul>${items.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`;
}

export function renderReportHtml(report) {
  const data = report.reportData ?? {};
  const performance = data.performance ?? {};
  const keywords = data.keywords ?? {};
  const audit = data.technicalHealth ?? {};
  const tasks = data.tasks ?? {};
  const period = `${new Date(report.periodStart).toLocaleDateString()} - ${new Date(report.periodEnd).toLocaleDateString()}`;
  const trafficRows = (performance.trend ?? []).map((row) => `<tr><td>${escapeHtml(row.date)}</td><td>${number(row.organicTraffic)}</td><td>${number(row.clicks)}</td><td>${number(row.impressions)}</td></tr>`).join("");
  const keywordRows = (keywords.topKeywords ?? []).map((item) => `<tr><td>${escapeHtml(item.keyword)}</td><td>${number(item.position)}</td><td>${item.change > 0 ? "+" : ""}${number(item.change)}</td></tr>`).join("");

  return `<!doctype html><html><head><meta charset="utf-8"><style>
    @page { size: A4; margin: 14mm; } * { box-sizing: border-box; } body { margin: 0; color: #172026; font: 12px Arial, sans-serif; }
    header { border-bottom: 3px solid #1f6feb; padding-bottom: 14px; margin-bottom: 18px; } h1 { margin: 0 0 5px; font-size: 25px; } h2 { margin: 20px 0 9px; font-size: 16px; } p { line-height: 1.55; }
    .muted, .metric span { color: #60717d; } .metrics { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; }
    .metric { border: 1px solid #dbe3ea; padding: 10px; border-radius: 5px; } .metric span, .metric strong { display: block; } .metric strong { margin-top: 5px; font-size: 18px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; } table { width: 100%; border-collapse: collapse; } th, td { border-bottom: 1px solid #dbe3ea; padding: 7px; text-align: left; } th { background: #f2f6f9; }
    ul { margin: 0; padding-left: 18px; } li { margin-bottom: 6px; } .empty { color: #60717d; } footer { margin-top: 24px; border-top: 1px solid #dbe3ea; padding-top: 9px; color: #60717d; }
  </style></head><body>
    <header><h1>${escapeHtml(report.title)}</h1><div class="muted">${escapeHtml(report.client.companyName)} | ${escapeHtml(period)} | ${escapeHtml(data.dataMode ?? "mock")} data</div></header>
    <h2>Executive Summary</h2><p>${escapeHtml(report.summary)}</p>
    <div class="metrics">
      ${metric("Organic Traffic", number(performance.organicTraffic))}${metric("Clicks", number(performance.clicks))}${metric("Impressions", number(performance.impressions))}${metric("Average Position", performance.averagePosition ?? 0)}
      ${metric("Improved Keywords", number(keywords.improved))}${metric("Completed Tasks", number(tasks.completed))}${metric("SEO Health", audit.averageScore ?? 0)}${metric("New Backlinks", number(data.backlinks?.newLinks))}
    </div>
    <div class="grid"><section><h2>Traffic Performance</h2><table><thead><tr><th>Date</th><th>Sessions</th><th>Clicks</th><th>Impressions</th></tr></thead><tbody>${trafficRows}</tbody></table></section>
    <section><h2>Top Keywords</h2><table><thead><tr><th>Keyword</th><th>Position</th><th>Change</th></tr></thead><tbody>${keywordRows}</tbody></table></section></div>
    <div class="grid"><section><h2>Technical SEO</h2>${list(audit.highlights, "No technical issues recorded.")}</section><section><h2>Completed Work</h2>${list(tasks.completedTitles, "No completed tasks recorded.")}</section></div>
    <h2>Recommendations and Next Priorities</h2>${list(data.recommendations, "No recommendations generated for this period.")}
    <footer>Generated by SEO Agency Platform on ${escapeHtml(new Date(report.createdAt).toLocaleString())}</footer>
  </body></html>`;
}

export class ReportPdfService {
  constructor({ storageDir = env.REPORT_STORAGE_DIR, executablePath = env.PUPPETEER_EXECUTABLE_PATH } = {}) {
    this.storageDir = path.resolve(storageDir);
    this.executablePath = executablePath || undefined;
  }

  filePath(reportId) {
    return path.join(this.storageDir, `${reportId}.pdf`);
  }

  async generate(report) {
    await mkdir(this.storageDir, { recursive: true });
    const browser = await puppeteer.launch({
      headless: true,
      executablePath: this.executablePath,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });
    try {
      const page = await browser.newPage();
      await page.setContent(renderReportHtml(report), { waitUntil: "networkidle0" });
      const outputPath = this.filePath(report.id);
      await page.pdf({ path: outputPath, format: "A4", printBackground: true, preferCSSPageSize: true });
      return { outputPath, pdfUrl: `/api/v1/reports/${report.id}/download` };
    } finally {
      await browser.close();
    }
  }

  async exists(reportId) {
    try { await access(this.filePath(reportId)); return true; } catch { return false; }
  }
}
