import { useState } from "react";
import { useAuth } from "../auth/AuthProvider.jsx";
import { createCompetitor, createWebsite, fetchWebsites } from "./websiteApi.js";

export function WebsitesPage(){
 const { accessToken }=useAuth(); const [clientId,setClientId]=useState(""); const [websites,setWebsites]=useState([]); const [selected,setSelected]=useState(null); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
 const [form,setForm]=useState({domain:"",cms:"WordPress",businessCategory:"",preferredLocale:"en-US",primaryCountry:"United States",targetLocations:"United States",targetSearchEngines:"google,bing",isMock:true});
 const [competitor,setCompetitor]=useState({domain:"",name:"",priority:"medium",source:"manual"});
 async function run(callback){setError("");setNotice("");try{await callback();}catch(err){setError(err.message);}}
 async function load(){if(!clientId)throw new Error("Client ID is required"); const data=await fetchWebsites(accessToken,clientId); setWebsites(data.websites);}
 async function submit(event){event.preventDefault(); await run(async()=>{await createWebsite(accessToken,clientId,{...form,targetLocations:form.targetLocations.split(",").map(v=>v.trim()).filter(Boolean),targetSearchEngines:form.targetSearchEngines.split(",").map(v=>v.trim()).filter(Boolean)}); setForm({...form,domain:""}); await load();});}
 return <main className="page-shell ops-page"><header className="page-header"><span>New-plan Day 4</span><h1>Website and Competitor Management</h1><p>Create website workspaces, store SEO settings, add competitors, and generate backlink placeholders.</p></header>
 <section className="ops-toolbar"><input placeholder="Client ID" value={clientId} onChange={(e)=>setClientId(e.target.value)}/><button onClick={()=>run(load)} type="button">Load websites</button></section>{error?<p className="auth-error keyword-error">{error}</p>:null}{notice?<p className="auth-notice keyword-error">{notice}</p>:null}
 <section className="ops-layout"><form className="ops-panel" onSubmit={submit}><h2>Add Website</h2><input placeholder="Domain" required value={form.domain} onChange={(e)=>setForm({...form,domain:e.target.value})}/><input placeholder="CMS" value={form.cms} onChange={(e)=>setForm({...form,cms:e.target.value})}/><input placeholder="Business category" value={form.businessCategory} onChange={(e)=>setForm({...form,businessCategory:e.target.value})}/><input placeholder="Locale" value={form.preferredLocale} onChange={(e)=>setForm({...form,preferredLocale:e.target.value})}/><input placeholder="Locations CSV" value={form.targetLocations} onChange={(e)=>setForm({...form,targetLocations:e.target.value})}/><input placeholder="Search engines CSV" value={form.targetSearchEngines} onChange={(e)=>setForm({...form,targetSearchEngines:e.target.value})}/><button type="submit">Create website</button></form>
 <div className="ops-panel"><h2>Websites</h2>{websites.map((website)=><button className="row-button" key={website.id} onClick={()=>setSelected(website)} type="button"><strong>{website.domain}</strong><span>{website.cms ?? "CMS"} · {website.businessCategory ?? "category"}</span></button>)}</div>
 <div className="ops-panel"><h2>Competitors</h2>{selected?<><p>{selected.domain}</p><div className="tab-list">{selected.tabs?.map(tab=><span key={tab.tab}>{tab.tab}</span>)}</div><input placeholder="Competitor domain" value={competitor.domain} onChange={(e)=>setCompetitor({...competitor,domain:e.target.value})}/><input placeholder="Name" value={competitor.name} onChange={(e)=>setCompetitor({...competitor,name:e.target.value})}/><button onClick={()=>run(async()=>{await createCompetitor(accessToken,selected.id,competitor);setNotice("Competitor added with backlink placeholder");await load();})} type="button">Add competitor</button>{selected.competitors?.map(item=><p key={item.id}>{item.domain} · backlinks {item.backlinks?.length ?? 0}</p>)}</>:<p>Select a website.</p>}</div></section></main>;
}
